In [5]:
import numpy as np
array = np.arange(1, 26).reshape(5, 5)
print("Array:\n", array)
array2 = array[1:4, 2:5]
print("\nSliced Subarray:\n",array2)
identity_matrix = np.eye(5,dtype='int16')
print("\nIdentity Matrix:\n", identity_matrix)


Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sliced Subarray:
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

Identity Matrix:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
