In [2]:
import numpy as np
arr1 = np.arange(1, 11)
print("Array:\n", arr1)
arr2 = arr1.reshape(2, 5)
print("\n2D Array:\n", arr2)
flattened_array = arr2.flatten()
print("\nFlattened Array:\n", flattened_array)


Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10]
