In [1]:
import numpy as np
matrix1 = np.random.randint(1, 51, (3, 3))
matrix2 = np.random.randint(1, 51, (3, 3))
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
add = matrix1 + matrix2
print("\nAddition:\n", add)
sub = matrix1 - matrix2
print("\nSubtraction:\n", sub)
mul= matrix1 * matrix2
print("\nMultiplication:\n", mul)
div = matrix1 / matrix2
print("\nDivision:\n", div)


Matrix 1:
 [[49 47 47]
 [49  2 23]
 [47 30  6]]

Matrix 2:
 [[32 37 33]
 [23 46 13]
 [24  9 42]]

Addition:
 [[81 84 80]
 [72 48 36]
 [71 39 48]]

Subtraction:
 [[ 17  10  14]
 [ 26 -44  10]
 [ 23  21 -36]]

Multiplication:
 [[1568 1739 1551]
 [1127   92  299]
 [1128  270  252]]

Division:
 [[1.53125    1.27027027 1.42424242]
 [2.13043478 0.04347826 1.76923077]
 [1.95833333 3.33333333 0.14285714]]
